### ISSUE TITLE
Use shorter path when displaying Microsoft Store Python envs when using native locator

### ISSUE THREAD

**Issue by luabud** [microsoft/python-environment-tools#132]
Testing microsoft/vscode-python#23848

when using the js locator, it used to find two versions of my Microsoft Store Python 3.9 environment: 

![Image](https://github.com/user-attachments/assets/581a534e-acbf-4d5e-b9b5-266433cf01f2)

The native finder shows only one, which is awesome! But it seems to prefer the one with the "longer" path: \AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe

![Image](https://github.com/user-attachments/assets/ff960230-158d-46de-8f0b-f667a883d031)

Ideally, it'd display this one: \AppData\Local\Microsoft\WindowsApps\python.exe

**Comment by DonJayamanne** [comment]
Fixed with https://github.com/microsoft/python-environment-tools/pull/133

**Comment by DonJayamanne** [comment]
@luabud Please can you re-test this with the latest version.

**Comment by DonJayamanne** [comment]
Verification steps
* Install Python extension on windows
* Install Python from Windows Store
* Ensure the path to the exe displayed for Windows Store python is `.../WindowsApp/Python3.x.exe`
* Ensure there are no duplicates (in the old version we'd display duplicates as per the original issue)

**Comment by brettcannon** [comment]
![image](https://github.com/user-attachments/assets/7eda7dba-92c3-4ed8-b04c-3dafd421951d)
