### ISSUE TITLE
Add env folders to env manager message

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-environment-tools#153]
Think conda envs folders, basically folders that are found in the conda env dirs when you run `conda info --json`

**Comment by DonJayamanne** [comment]
Please can you share some examples or more context, as I'm unable to understand the requirements above.

**Comment by karthiknadig** [comment]
In the conda locator, you find the env directories. Can you add that to the message sent back by pet:
![image](https://github.com/user-attachments/assets/db8747f9-dc35-403f-8647-1e3ba3cffd34)

**Comment by DonJayamanne** [comment]
unless you have come across a situation where this doesn't work, i'm closing this as this has been done today..

**Comment by DonJayamanne** [comment]
After discussion decided that we'd not return these, instead Python extension will make necessary changes to get around this requirement.
