### ISSUE TITLE
Add any other bin dirs for environment managers

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/python-environment-tools#154]
This is specifically for `condabin` dir, after conda is found.

This is important to have path to `conda.bat` which is used for activating conda envs (cases where `conda init` is not called)  and running conda using `conda run`.

**Comment by DonJayamanne** [comment]
Please can you provide more infromation, as I cannot understand the requirement here.

**Comment by karthiknadig** [comment]
Currently, you detect and return path to `conda.exe`, for shell executions, the recommendation is to use `conda.bat`. This is typically found in `condabin` directory in the same level as `conda.exe` . Can you add this to the message sent back about environment managers.

**Comment by DonJayamanne** [comment]
After discussion decided that we'd do this in Python extension for now.
