### ISSUE TITLE
Native finder misses some global/miniconda/venv on new user data dir

### ISSUE THREAD

**Issue by rebornix** [microsoft/python-environment-tools#43]
Testing microsoft/vscode-python#23482

Tested this against a new use data dir and the native doesn't find .venv, some global python or miniconda.

<img width="611" alt="image" src="https://github.com/microsoft/vscode-python/assets/876920/be25c99c-f412-48bf-b81e-e362fed31520">

<img width="618" alt="image" src="https://github.com/microsoft/vscode-python/assets/876920/6d3111a8-ce6b-40e9-8cf9-fa38c6369427">

**Comment by DonJayamanne** [comment]
@rebornix Please can you test this again using the native locator in the latest pre-release of Python extension and very it has been resolved
Thanks

**Comment by DonJayamanne** [comment]
Closing as stale
