### ISSUE TITLE
Description of features, behavior, etc

### ISSUE THREAD

**Issue by oaustegard** [microsoft/python-environment-tools#98]
Neither the announcement in the June 2024 (version 1.91) VS Code release notes, nor the README.MD actually describe the features, benefits and behavior of this tool. Seems worth adding?

**Comment by smp73** [comment]
Just my name

**Comment by qarlosalberto** [comment]
Please, could you add some kind of documentation on how to use it in my own extension? Thanks.

**Comment by bionicles** [comment]
yeah, README needs an update, not clear how to install and configure and use this, do we use cargo, is it built into vs code, ... looks like a solid project, please take 25 minutes to put usage instructions

**Comment by cwebster-99** [comment]
This project will be consumed by the Python extension directly. You can find the code to consume `pet` in the Python extension [source code](https://github.com/microsoft/vscode-python/blob/main/src/client/pythonEnvironments/base/locators/common/nativePythonFinder.ts). 

For more information on JSNORPC requests/notifications for this tool, please reference [/docs/JASONRPC.md](https://github.com/microsoft/python-environment-tools/blob/main/docs/JSONRPC.md).
